name = "nael"
description = "Nael Audio Experimentation Lab"
version = "0.1.0-dev"

authors = ["Fabien Chouteau"]
maintainers = ["Fabien Chouteau <fabien.chouteau@gmail.com>"]
maintainers-logins = ["Fabien-Chouteau"]

[[depends-on]]
gtkada = "^23.0.0"
aicwl = "^3.24.1"
aaa = "~0.2.6"

[environment.'case(distribution)'.msys2.CPLUS_INCLUDE_PATH]
append = "${DISTRIB_ROOT}/mingw64/include"
